{
 "title": "Sentry Issues & Events Overview",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "project",
    "label": "project",
    "query": {
     "query": "label_values(sentry_open_issue_events, project_slug)"
    }
   },
   {
    "name": "environment",
    "label": "environment",
    "query": {
     "query": "label_values(sentry_open_issue_events{project_slug=~\"$project\"}, environment)"
    }
   },
   {
    "name": "release",
    "label": "release",
    "query": {
     "query": "label_values(sentry_open_issue_events{project_slug=~\"$project\"}, release)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total number of New Issues",
   "type": "stat",
   "description": "Total number of new issues open in the past 1h",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sentry_open_issue_events{project_slug=~\"$project\", release=~\"$release\", environment=~\"$environment\"})",
     "legendFormat": "Issues"
    }
   ]
  },
  {
   "title": "Total events (per sec)",
   "type": "stat",
   "description": "Total events per second in 30 minutes vector",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(sentry_events_total{project_slug=~\"$project\"}[30m]))",
     "legendFormat": "events"
    }
   ]
  },
  {
   "title": "Total events in new issues (last 24h)",
   "type": "stat",
   "description": "Total number of events in new issues in the past 24h range",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(sentry_issues_bucket{project_slug=~\"$project\", environment=~\"$environment\",le=\"24h\"})",
     "legendFormat": "events"
    }
   ]
  },
  {
   "title": "New issues by project (last 1h)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum(sentry_issues_bucket{project_slug=~\"$project\", environment=~\"$environment\", le=\"1h\"}) by (project_slug)",
     "legendFormat": "{{ project_slug }}"
    }
   ]
  },
  {
   "title": "New Issues by release",
   "type": "table",
   "description": "Total number of new issues by project release",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 5 },
   "targets": [
    {
     "expr": "sum(sentry_open_issue_events{project_slug=~\"$project\", release=~\"$release\", environment=~\"$environment\"}) by (project_slug, release, environment)",
     "legendFormat": "{{ project_slug }}: {{ release }}"
    }
   ]
  },
  {
   "title": "New Issues by project",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sentry_open_issue_events) by (project_slug)",
     "legendFormat": "{{ project_slug }}"
    }
   ]
  },
  {
   "title": "New Issues by environment",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sentry_open_issue_events{project_slug=~\"$project\", release=~\"$release\", environment=~\"$environment\"}) by (environment)",
     "legendFormat": "{{ environment }}"
    }
   ]
  },
  {
   "title": "Events by project (per sec)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(sentry_events_total[30m])) by (project_slug)",
     "legendFormat": "{{ project_slug }}"
    }
   ]
  }
 ]
}