apiVersion: v1
kind: Service
metadata:
  name: {{ include "sentry-prometheus-exporter.fullname" . }}
  labels:
    {{- include "sentry-prometheus-exporter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    # - port: {{ .Values.service.port }}
    #   targetPort: http
    #   protocol: TCP
    #   name: http
    - port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "sentry-prometheus-exporter.selectorLabels" . | nindent 4 }}
